### ISSUE TITLE
Add bias correction for local MI/TE values

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jlizier/jidt#18]
```
Add these as an option that can be turned on in properties.

See description by Turney and Pantel (2010), which is cited in our 2014 
Frontiers paper on Local Active Info Storage


```

Original issue reported on code.google.com by `joseph.lizier` on 28 Jan 2014 at 5:02

**Comment by jlizier** [comment]
This is implemented for KSG (natively) and Guassian (by removing analytic mean bias) estimators now. Bias correction is not estimated on other estimators; if and when it is, will be added locally as well.
So, closing issue.
