### ISSUE TITLE
Java demos should be distributed with compiled class files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jlizier/jidt#44]
```
Fix this in the ant file -- make the dist target compile these and retain them 
for the distribution.


```

Original issue reported on code.google.com by `joseph.lizier` on 20 Jul 2015 at 11:29

**Comment by jlizier** [comment]
Rejected -- it makes sense to include the class files for the AutoAnalyser (the user may not wish to write code) as done in #49, but I don't see any point letting the user run these code demos if they're not able to compile new code to do other things later.
