### ISSUE TITLE
GPU issue when local variable is destroyed

### ISSUE THREAD

**Issue by nstrodt** [jlizier/jidt#59]
I like jidt very much and I recently started looking into the new GPU feature as my computational demands could profit a lot from it. I am using jidt via jpype to estimate mutual information via the Kraskov algorithm. This works perfectly as long as the context of the data array that is passed to set_observations is not destroyed (this happens for example when saving to a local variable in a loop). At this point the stream is left in the state CUDA_ERROR_CONTEXT_IS_DESTROYED and the jre crashes with a segmentation fault. For USE_GPU = False the code runs without any problems.

It would be nice if you could look into this issue or give me a hint what is going wrong here. Please contact me if you need further information.

**Comment by pmediano** [comment]
Hi @nstrodt , thanks a bunch for the bug report. Could you provide a minimal example script that reproduces the crash?

**Comment by nstrodt** [comment]
Thanks for getting back to me so quickly. I seem to have jumped to a conclusion to quickly. As far as I can see this issue arose from interference with another process accessing CUDA in the same python file.
Thanks again.
