### ISSUE TITLE
infodynamics.jar Missing in the Distribution 

### ISSUE THREAD

**Issue by zhiyuan-jia** [jlizier/jidt#91]
infodynamics.jar Library file is missing in the top level folder in the latest distribution

**Comment by jlizier** [comment]
I presume you have clicked the code | Download Zip button on the home page. That just gives you a copy of the repo (which does not have the jar), it's not a distribution. The latest [distribution](https://github.com/jlizier/jidt/releases/tag/v1.5) certainly has the jar in it.
