### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by AdelleBernal** [jlizier/jidt#96]
Does this toolbox generate plots for visualisation of information flow measures?
Great work, thanks!

**Comment by jlizier** [comment]
No, it's a calculation engine.

Some of the [demos](https://github.com/jlizier/jidt/wiki/Demos) have visualisations for specific use-cases, e.g. for info flow in [cellular automata](https://github.com/jlizier/jidt/wiki/CellularAutomataDemos) or in [swarms/flocks](https://github.com/jlizier/jidt/wiki/Flocking).
